version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LLM_SERVER=http://llm:8001

  llm:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 