name: Deploy to GPU Instance

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure Vultr credentials
      env:
        VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
      run: |
        # Install Vultr CLI
        curl -fsSL https://download.vultr.com/vultr-cli/install.sh | bash

    - name: Deploy to Vultr GPU instance
      run: |
        vultr-cli instance create \
          --plan vhf-6c-32gb-1rtxa6000 \
          --region ewr \
          --os 387 \  # Ubuntu 20.04
          --label "gmail-assistant-gpu" \
          --tag "production"